version: '3'

services:

  quick:
    build: .
    ports:
      - "80:80"
    env_file:
      - variables.env

  frontend:
    image: andriiiiiko/quick-link-frontend:latest
    ports:
      - "3000:3000"

  pgadmin:
    image: elestio/pgadmin
    restart: always
    env_file:
      - variables.env
    ports:
       - "8080:8080"
    volumes:
        - ./servers.json:/pgadmin4/servers.json
