version: '3'

services:

  quick:
    build: .
    ports:
      - 8080:8080
    env_file:
      - variables.env

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    env_file:
      - variables.env
